name: ligo-py27
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/free
dependencies:
  - python=2.7
  # common build tools
  - autoconf
  - automake
  - bc
  - blas
  - compilers
  - cmake
  - gsl
  - pkg-config
  - swig
  - wget
  # python tools
  - flake8
  - ipython
  - jupyter
  - pyflakes
  - pylint
  # lscsoft packages
  - bayeswave
  - bayeswaveutils
  - bilby
  - bruco
  - cpnest
  - dqsegdb
  - dqsegdb2
  - gpstime
  - gwdatafind
  - gwdetchar
  - gwosc
  - gwpy
  - gwsumm
  - hveto
  - kombine
  - lalsuite
  - lal
  - ldas-tools-al
  - ldas-tools-diskcacheapi
  - ldas-tools-filters
  - ldas-tools-frameapi
  - ldas-tools-framecpp
  - ldas-tools-ldasgen
  - libframe
  - ligo-gracedb
  - ligo-lvalert
  - ligo-segments
  - ligotimegps
  - lscsoft-glue
  - metaio
  - nds2-client
  - pycbc
  - python-ldas-tools-al
  - python-ldas-tools-framecpp
  - python-ldas-tools-ldasgen
  - python-ligo-lw
  - python-nds2-client
  - rift
  - virtualenv
